ENT.Base 			= "sent_vj_hlr_alientp"
ENT.Type 			= "anim"
ENT.PrintName 		= "Random Race X Spawner"
ENT.Author 			= "DrVrej"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Purpose 		= "Spawn it and fight with it!"
ENT.Instructions 	= "Click on the spawnicon to spawn it."
ENT.Category		= "VJ Base Spawners"