ENT.Base = "npc_vj_creature_base"
ENT.Type = "ai"
ENT.PrintName = "Dreamcast Houndeye"
ENT.Author = "DrVrej"
ENT.Contact = "http://steamcommunity.com/groups/vrejgaming"
ENT.Category = "Half-Life Resurgence"